curso = "Curso de Python"
print(curso[0:5])
print(curso[6:8])
print(curso[9:15])
print(curso.strip())
print(curso.lower().strip())
print(curso.upper().strip())
print(curso.replace("Python", "C#"))
print("Tamanho: " + str(len(curso)))
a = curso.split(" ")
print(a[0])
print(a[1])
print(a[2])
print(curso[0])
print(curso[1])
print(curso[2])
print(curso[3])
print(curso[4])
print(curso[5])
print(curso[6])
print(curso[7])
print(curso[8])
print(curso[9])
print(curso[10])
print(curso[11])
print(curso[12])
print(curso[13])
print(curso[14])
print(curso[15])